version: '3'

networks:
  client_2:

services:

### NGINX ################################################
  nginx3:
    build: ./nginx
    ports:
      - "8001:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php3
      - mysql3
    networks:
      - client_2

### MySQL ################################################
  mysql3:
    build: ./mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: client_2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - client_2

### PHP ################################################
  php3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www
    ports:
      - "9002:9000"
    networks:
      - client_2

      ### phpMyAdmin ###########################################

  phpmyadmin3:
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=sso
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8083:80
    depends_on:
      - mysql3
    networks:
      - client_2