version: '3'

networks:
  client_1:

services:

### NGINX ################################################
  nginx2:
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
      - mysql2
    networks:
      - client_1

### MySQL ################################################
  mysql2:
    build: ./mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: client_1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - client_1

### PHP ################################################
  php2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www
    ports:
      - "9001:9000"
    networks:
      - client_1

      ### phpMyAdmin ###########################################

  phpmyadmin2:
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=sso
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8082:80
    depends_on:
      - mysql2
    networks:
      - client_1