version: '3'

networks:
  sso_server:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - sso_server

### MySQL ################################################
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sso_server
      MYSQL_USER: sso
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - sso_server

### PHP ################################################
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www
    ports:
      - "9000:9000"
    networks:
      - sso_server

### phpMyAdmin ###########################################

  phpmyadmin:
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=sso
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8081:80
    depends_on:
      - mysql
    networks:
      - sso_server